### ISSUE TITLE
Better documentation in README.md

### ISSUE THREAD

**Issue by zaqk** [demisto/demisto-py#11]
Hi! Thanks, for the library. I think it would be helpful if there were instructions to install this library from pip (I see a version on pip under the name "demistoapi") and if there were more information about versioning. Also, is this SDK compatible with python 3?

**Comment by dorsha** [comment]
I @zaqk, at the moment, we don't release the demisto-py SDK via PyPI, what you see there (demistoapi) is maintained outside Demisto by one of our users.
The SDK is compatible with Python 3.

**Comment by zaqk** [comment]
@dorsha got it. thanks!
