### ISSUE TITLE
Search Incident By Occurred Date-Time

### ISSUE THREAD

**Issue by LC40** [demisto/demisto-py#13]
Hi Devs and all,

  I am facing an issue where I am trying to search an incident that happened in the past couple of days. However, if I try to use `client.SearchIncidents(0,100,'name:test')` and search by the name it works. If I try to put in `client.SearchIncidents(0,100,'2019-07-31T13:00:00Z')` it returns no results despite the system having multiple incidents. 

I also tried to use a post request technique found with indicators for incidents and am getting a 500 Internal Server Error (Yet to check logs with my admin). 

```
    options = options_handler()
    c = demisto.DemistoClient(options.key, options.server)
    postData = {'sort': [{'field': 'value', 'asc': True}]}
    postData['fromDate'] = fromDate(options.delta)
    indicatorsResponse = c.req('POST', 'incidents/search', postData)
    if indicatorsResponse.status_code != 200:
        raise RuntimeError('Error getting incidents data - %d (%s)' %(indicatorsResponse.status_code, indicatorsResponse.reason))
    indicators = indicatorsResponse.json()
    print(json.dumps(indicators, indent=4, sort_keys=True))
```

Any help is greatly appreciated! 

P.S Is there a way to run a external python script like via Demisto every time a new incident occurs?

**Comment by LC40** [comment]
UPDATE:

I have edited the code and fixed some errors but still getting no result.

Code:
```
    options = options_handler()
    testvar = 'fromDate:' + fromDate(options.delta)
    c = demisto.DemistoClient(options.key, options.server)
    postData = {'filter': {'query': testvar}}
    #postData['toDate'] = fromDate(options.delta)
    print(testvar)
    print(json.dumps(postData, indent=4, sort_keys=True))
    indicatorsResponse = c.req('POST', 'incidents/search', postData)
    if indicatorsResponse.status_code != 200:
        raise RuntimeError('Error getting incidents data - %d (%s)' %(indicatorsResponse.status_code, indicatorsResponse.reason))
    indicators = indicatorsResponse.json()
    print(json.dumps(indicators, indent=4, sort_keys=True))
```
Output:
```
fromDate:2019-07-28T11:01:41Z
{
    "filter": {
        "query": "fromDate:2019-07-28T11:01:41Z"
    }
}
{
    "data": [],
    "notUpdated": 0,
    "total": 0
}

```

**Comment by glicht** [comment]
You can use: `client.SearchIncidents` with a query of the form: `created:>="2019-08-01T00:00:00Z"`.

For example in your code you can do something fo the sort:
```python
incidents = c.SearchIncidents(0, 100, 'created:>="{}"'.format(fromDate(options.delta)))
```

**Comment by glicht** [comment]
you can see an example at: https://github.com/demisto/demisto-py/blob/incidents-search-example/incidents_search_example.py
