### ISSUE TITLE
Feature request: extend upload_content_packs method to allow reattaching content

### ISSUE THREAD

**Issue by tlium** [demisto/demisto-py#140]
**Describe the bug**
When using demisto-py and demisto-sdk I often find myself having to detach content, especially playbooks. 
It would be very nice if the upload_content_packs method in demisto-py allowed me to automatically reattach content when uploading a content pack.

**To Reproduce**
1. Detach playbook, do modifications, download and move it to the proper content pack
2. Upload the modified content pack from a python script using demisto-py
3. Detached content is still detached

**Expected behavior**
I would like a new argument to the upload_content_packs method to allow me to automatically reattach detached content.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by tlium** [comment]
Hey @amshamah419. Is this feature request something you want to consider?
Apparently the functionality is already implemented in demisto-sdk with `demisto-sdk upload --reattach`, but my CI flows use demisto-py for deploying content packs to the server. What do you think? Do I need to change my CI workflows or is there some chance this feature request will be picked up in demisto-py?

**Comment by amshamah419** [comment]
Hi @tlium let me check with our product team to see if this is something we can prioritize. 

@dorschw My feeling is that if we take care of this on the demisto-py level, it may simplify the process in the sdk, wdyt?

**Comment by dorschw** [comment]
Hey @tlium, Please submit feature requests in [Aha](https://xsoar.ideas.aha.io/ideas), where product management prioritize features, and other customers can vote on them.

**Comment by tlium** [comment]
Aha.io, where ideas go to die :(
