### ISSUE TITLE
API doesn't return full list of incidents

### ISSUE THREAD

**Issue by Elhitch** [demisto/demisto-py#46]
**Describe the bug**
I am trying to get all closed incidents from a certain period of time, for example the last 7 days. However, my script doesn't return a complete list of incidents and some are omitted. My code is as follows:

```
import demisto_client.demisto_api
from demisto_client.demisto_api.rest import ApiException
import urllib3
from datetime import datetime
from datetime import timedelta
import dateutil.parser as dparser
import pytz

# Get start and end of report
reportEndDate = pytz.UTC.localize(datetime.today()).replace(hour=0, minute=0, second=0, microsecond=0)
reportStartDate = pytz.UTC.localize((datetime.today() - timedelta(days=7)).replace(hour=0, minute=0, second=0, microsecond=0))

# Configure connection-related parameters and create an API instance
urllib3.disable_warnings()
api_key = '...'
host = 'https://...'
DEMISTO_VERIFY_SSL = False
api_instance = demisto_client.configure(base_url=host, api_key=api_key, debug=False, verify_ssl=DEMISTO_VERIFY_SSL)

incidentsClosedThisWeek = []
lastIncidentCloseTime = reportStartDate

# Since the API returns only 25 incidents, create new requests once per every 25 incidents. To create a new request, get the closed date of the incident closed last. Append all results to a list
iterate = True
while iterate:
	print ("Starting to iterate from datetime:", lastIncidentCloseTime)
	filter = demisto_client.demisto_api.SearchIncidentsData()
	inc_filter = demisto_client.demisto_api.IncidentFilter()
	inc_filter.from_closed_date = lastIncidentCloseTime
	inc_filter.sort = [{"asc": True, "field": "id"}]
	filter.filter = inc_filter
	api_response = api_instance.search_incidents(filter=filter)
	data = api_response["data"]
	for i in range(len(data)):
		incidentsClosedThisWeek.append(data[i])
	if len(data) == 25:
		for i in range(25):
			if lastIncidentCloseTime < dparser.parse(data[i]["closed"]):
				lastIncidentCloseTime = dparser.parse(data[i]["closed"])
		data = None
	else:
		iterate = False

# Fill a list of IDs from each incident (this is to demonstrate the issue, the rest of the code is from my actual script)
incidentIDS = []
for incident in incidentsClosedThisWeek:
    if incident["id"] not in incidentIDS:
        incidentIDS.append(incident["id"])
print(incidentIDS)
```

**To Reproduce**
1. Copy the code snippet above
2. Modify the connection parameters
3. Run the script and check for missing incidents

**Expected behavior**
All closed incidents should appear but instead some (most) are missing.

**Environment**
 - Python Version: Windows - 3.7.8, Linux - 3.6.8
 - OS: Irrelevant, tested on Windows and Linux
 - Demisto Version: 5.5.0 70066
 - Content Version: 20.7.0 (61242)

**Additional context**
For some reason, if I just get the closed time of the last incident of the batch, e.g.:
```
	if len(data) == 25:
		lastIncidentCloseTime = dparser.parse(data[24]["closed"])
```

Then more incidents appear in the list which makes me think that's a bug with the API. Furthermore, a similar issue appears when I remove the sort filter - then there are less incidents coming back for some reason (even though the sort shouldn't affect the total number of incidents returned by Demisto).

**Comment by glicht** [comment]
The issue here is that you are sorting on the `id` field but using the `closed` field to advance the iteration. This causes you to skip date ranges. You should probably sort on the `closed` field.

**Comment by Elhitch** [comment]
Hi @glicht,

Thank you for your quick reply. That makes sense and it does seem to work as expected.  I can now see the flaw in the logic (you could get the date/time of the last closed incident in the batch as I do in the script above, but that doesn't guarantee that an incident with a higher ID wasn't closed earlier, thus skipping the incident).

Thanks for your help and sorry for the pointless issue.

Best regards :)
