### ISSUE TITLE
Incident model doesn't match answer from API

### ISSUE THREAD

**Issue by smadessis** [demisto/demisto-py#50]
Hi Demisto team,

I'm trying to gather incidents from Cortex XSOAR and perform filtering on it by transforming the object to Python dictionnary.
However, the model of "Incident" doesn't match the answer I get from Cortex XSOAR. 
There is no proprety "CustomFields" for the object, while it's present in the answer.
https://github.com/demisto/demisto-py/blob/95ed78223eb89f2079ce222b0d25ef39868dc9fb/demisto_client/demisto_api/models/incident.py#L40

The original API documentation also doesn't seem correct, and only mention this proprety for IocObject while it's also present for Incidents.

IoC object has indeed the proprety CustomFields:
https://github.com/demisto/demisto-py/blob/95ed78223eb89f2079ce222b0d25ef39868dc9fb/demisto_client/demisto_api/models/ioc_object.py

How to reproduce:
[...]
api_response = api_instance.search_incidents(filter=filter)
incidents = api_response.data
print(api_response) #This shows CustomFields field is indeed present, while it doesn't show up in the model

**Comment by glicht** [comment]
Thanks for reporting this. We will check regarding adding this to the model.
