### ISSUE TITLE
API for executing single command on single Incident (war room)

### ISSUE THREAD

**Issue by nguyenl95** [demisto/demisto-py#51]
I was looking for an API to execute command on war room of an incident. But I couldn't find any documents.

Example:
I'm using QRADAR integration module, there is a command `!qr-offenses`.
Now I want to call the above command by using this library.

I really appreciate your help!

**Comment by meirwah** [comment]
![image](https://user-images.githubusercontent.com/6059211/94244205-35cf4080-ff21-11ea-9ef4-cbaa1211a673.png)

add this suffix to get the info:
![image](https://user-images.githubusercontent.com/6059211/94244255-47b0e380-ff21-11ea-8b52-d254f940ada0.png)

**Comment by meirwah** [comment]
@nguyenl95 let me know if you still have issues

**Comment by nguyenl95** [comment]
Thanks, that was very clear to me.
