### ISSUE TITLE
API doesn't return notes

### ISSUE THREAD

**Issue by Elhitch** [demisto/demisto-py#52]
Hi, it looks like when search_incidents is used, the response doesn't contain the notes within the matched incident(s). Is this supported and am I doing something wrong?

**Comment by glicht** [comment]
Not sure what you mean by "notes". Can you provide more details.

**Comment by Elhitch** [comment]
Hi, in the screenshot below (from a demo Demisto environment, not our own) you can see the Notes widget in the center of the screen.

![image](https://user-images.githubusercontent.com/7511627/94661150-5deae500-030f-11eb-8964-872e54299c1a.png)

**Comment by glicht** [comment]
@Elhitch this API is currently not supported by demisto-py.

You can use the generic request to fetch this data. It is stored under investigation in the `entries` field.

For example:
```python
# create api_instance based on env variables
api_instance = demisto_client.configure()

# fetch an investigation according to it's id (the id can obtained from the incident). For example an id of 50
(res, status, headers) = api_instance.generic_request('/investigation/50', 'POST', {"pageSize":100},  response_type='object' )
# res['entries'] will contain the war room data. The `note` will be true for relevant notes. For example you can print all relevant entries:
print(list(filter(lambda a: a.get('note', False) is True, res['entries'])))
```
