### ISSUE TITLE
API to run system commands on playground

### ISSUE THREAD

**Issue by nguyenl95** [demisto/demisto-py#55]
Hi guys,

I'm looking for an API to run system commands on the playground or playbooks.

I tried out `investigation_add_entries_sync` and `UpdateEntry` functions but it just didn't work.

My end goal is to run these system commands `investigation_close` and `investigation_reopen`.

Appreciate your help!

**Comment by glicht** [comment]
@nguyenl95 these APIs are not officially exposed via our swagger interface, thus not included in this library. You can call the `generic_request` function though. You can see an example how to use `generic_request`  here: https://github.com/demisto/demisto-py/blob/master/tests/mocks_test.py#L224

You are also welcome to add a feature request to add additional APIs to our swagger definition at: http://xsoar.ideas.aha.io/ .
