### ISSUE TITLE
Create indicators from JSON - is missing e.g. POST /indicators/feed/json

### ISSUE THREAD

**Issue by gomesian** [demisto/demisto-py#59]
**Describe the bug**
I notice 'create indicators from JSON' endpoint is missing e.g. POST /incident/json
I now have a mix of demisto-py and REST API code. Hopefully some plans to add?

**Expected behavior**
demisto-py follows published REST API

**Environment**
Version 6.1.0

**Comment by glicht** [comment]
@gomesian sorry for the delayed response. The api is available via the method: `create_incident_json`

See: https://github.com/demisto/demisto-py/blob/master/demisto_client/demisto_api/api/default_api.py#L807

**Comment by gomesian** [comment]
Very sorry.. I made a typo. I meant **Indicators** JSON is missing..
POST /indicators/feed/json - Not found here: https://github.com/demisto/demisto-py/blob/master/docs/README.md
But documented in XSOAR API docs 6.1_beta and I think 6.0.1

**Describe the bug**
I notice 'create indicators from JSON' endpoint is missing e.g.  **POST /indicators/feed/json**

**Comment by gomesian** [comment]
Looks like I cant re-open..

**Comment by glicht** [comment]
@gomesian understood. We will add.
