### ISSUE TITLE
Naïve Cookie assumption

### ISSUE THREAD

**Issue by BGarber42** [demisto/demisto-py#68]
**Describe the bug**
Code assumes the CSRF token is the first cookie returned by the server, this breaks if there's any sort of LB or caching in front of Demisto

**To Reproduce**
1.  Proxy Demisto through anything that sets a cookie
2. See error

**Expected behavior**
Script can log in successfully

**Error**
`HTTP response body: {"id":"forbidden","status":403,"title":"Forbidden","detail":"Issue with CSRF code","error":"http: named cookie not present","encrypted":false,"multires":null}
`

**Comment by meirwah** [comment]
@BGarber42 not sure I fully follow here
is this a bug ? a question?

any customer encountered it ?

which LB/cache you used which broke in this case ?
we have multiple customers using proxy/LB in front of their Demisto server

**Comment by BGarber42** [comment]
To expand, if you use an AWS ALB, it sets it's own cookies for sessions. [The code](https://github.com/demisto/demisto-py/blob/master/demisto_client/__init__.py#L129) will just look at the first Set-Cookie header and try to use string manipulation to extract out the value rather than use [builtins](https://docs.python.org/3/library/http.cookiejar.html)

**Comment by jochman** [comment]
Hey @BGarber42, I'm taking care of the issue.
Anyway, I suggest you to move to [API-Key authentication](https://github.com/demisto/demisto-py#1-get-a-demisto-api-key) instead of basic auth.

**Comment by jochman** [comment]
I'll be happy to hear about it! 
On which endpoints and the error message.
