### ISSUE TITLE
ApiKey not used on Login

### ISSUE THREAD

**Issue by SHSauler** [demisto/demisto-py#7]
I could be mistaken, but from reading it, the `apiKey` is never used to login and only username and password are.

https://github.com/demisto/demisto-py/blob/b4c27a46b037ee940f9ce3f641afff63174d9c17/demisto/client.py#L64

**Comment by meirwah** [comment]
@SHSauler the API key is used here:
https://github.com/demisto/demisto-py/blob/master/demisto/client.py#L53

Note that you don't need the Login() funcation when you have given an apiKey argument

**Comment by SHSauler** [comment]
Oh, I see. Thanks for clarifying!
