### ISSUE TITLE
Setting `CreateIncidentRequest.source_brand` has no affect in XSOAR

### ISSUE THREAD

**Issue by mbremerkamp** [demisto/demisto-py#71]
**Describe the bug**
The XSOAR platform appears to ignore the `CreateIncidentRequest.source_brand` member field. Setting a custom `source_brand` when creating an incident request seems to have no affect in the actual XSOAR platform.

**To Reproduce**
1.  Create an incident request
2. Set the `source_brand` field to something other than "Manual"
3. Upload the newly created incident to an XSOAR test server
4. Click on the incident in XSOAR
5. The incident's `source_brand` is always set to "Manual"

**Expected behavior**
The newly created incident in XSOAR should have a `source_brand` field equal to what was set in the `CreateIncidentRequest`.

**Screenshots**
![Incorrect_soruce_brand](https://user-images.githubusercontent.com/14205233/137537761-ef02783d-a556-4d5d-b3f4-1f4b92c51a8a.png)

**Environment**
 - Python Version: 3.8.11
 - OS: MacOs Big Sur 11.5.2
 - Demisto Version: 3.0.2

**Additional context**
I'm not 100% sure if this is an issue with the demisto sdk or a problem with the XSOAR server itself. Feel free to close this issue out if it is the latter, and nothing can be done here.

**Comment by anara123** [comment]
It is possible.  But according to the implementation you should additionally add an Instance label.
So pass labels to the incident `[{"type":"Instance","value":"FILL_INSTANCE"}]`
