### ISSUE TITLE
When the api key is wrong- the reponse from server is wrong and not useful

### ISSUE THREAD

**Issue by PaulAnton** [demisto/demisto-py#8]
{"id":"forbidden","status":403,"title":"Forbidden","detail":"Issue with CSRF code","error":"http: named cookie not present","encrypted":false,"multires":null}

It would be more helpful if the error and detail informs that the apikey is wrong.

**Comment by kp625544** [comment]
Ping! still the same issue

**Comment by glicht** [comment]
Thanks for the ping. We have plans to upgrade this package and improve usability. We will be addressing this then.
