### ISSUE TITLE
Function `get_stats_for_widget` is not properly implemented

### ISSUE THREAD

**Issue by nb-pdragoi** [demisto/demisto-py#82]
**Describe the bug**
Accord to the docs from [here](https://github.com/demisto/demisto-py/blob/master/docs/DefaultApi.md#get_stats_for_widget), the function to get widget statistics should be pretty to call. However, it does not require any widget id, name, json or anything, which the api endpoint requires. After looking into the function implementation [here](https://github.com/demisto/demisto-py/blob/master/demisto_client/demisto_api/api/default_api.py), we can see that nothing is parsed into the `body_params` of the `get_stats_for_widget_with_http_info` function.

**To Reproduce**
1. Run the code from the [example](https://github.com/demisto/demisto-py/blob/master/docs/DefaultApi.md#get_stats_for_widget),
2. See error
```
Exception when calling DefaultApi->get_stats_for_widget: (400)
Reason: Bad Request
HTTP response body: {"id":"bad_request","status":400,"title":"Bad request","detail":"Request body is not well-formed. It must be JSON.","error":"EOF","encrypted":false,"multires":null}
```

**Expected behavior**
Get the results from the widget.

**Environment**
 - Python Version: 3.7-3.9
 - OS: Linux
 - Demisto Version: 6.5

**Additional context**
Same issue is with the `get_stats_for_dashboard` function: no way to set the dashboard we want to make the request to.

**Comment by pdragoi** [comment]
Was this fixed?
